---
# tasks file for squid

- name: Ensure squid is installed
  yum:
    name: squid
    state: present

- name: Configure squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    validate: squid -k parse %s
  notify: restart squid

- name: Ensure squid is started and enabled
  service:
    name: squid
    state: started
    enabled: true
